name: 'olist_ecommerce'
version: '1.0.0'
config-version: 2

profile: 'olist_ecommerce'

model-paths: ['models']
test-paths: ['tests']
snapshot-paths: ['snapshots']
macro-paths: ['macros']

models:
  olist_ecommerce:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
