version: 2

models:
  - name: customer_lifetime_value
    columns:
      - name: customer_id
        tests:
          - not_null
      - name: customer_segment
        tests:
          - not_null

  - name: cohort_analysis
    columns:
      - name: cohort_month
        tests:
          - not_null

  - name: product_performance
    columns:
      - name: product_id
        tests:
          - not_null
      - name: total_revenue
        tests:
          - not_null
